version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn        

      - run: yarn workspace gatsby-mdx test
      - run: yarn workspace babel-plugin-gather-exports test
      - run: yarn workspace babel-plugin-pluck-imports test
      - run: yarn workspace babel-plugin-pluck-exports test
      - run: yarn lint
  publish:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: yarn publish-ci
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: /^master$/
            
